language: node_js
node_js:
  - 4.3
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
  secret_access_key: $AWS_SECRET_KEY
  bucket: zllvm-sunnyday
  endpoint: http://zllvm-sunnyday.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  skip_cleanup: true
  acl: public_read
  detect_encoding: true
  on:
    branch: master
script: 
  - make build    
notifications:
  email:
    on_failure: always
